
export const GET_PRODUCT_PROGRESS="GET_PRODUCT_PROGRESS";
export const GET_PRODUCT_SUCESS="GET_PRODUCT_SUCESS";
export const GET_PRODUCT_ERROR="GET_PRODUCT_ERROR";

export const POST_PRODUCT_PROGRESS="POST_PRODUCT_PROGRESS";
export const POST_PRODUCT_SUCESS="POST_PRODUCT_SUCESS";
export const POST_PRODUCT_ERROR="POST_PRODUCT_ERROR";

export const DELETE_PRODUCT_PROGRESS="DELETE_PRODUCT_PROGRESS";
export const DELETE_PRODUCT_SUCESS="DELETE_PRODUCT_SUCESS";
export const DELETE_PRODUCT_ERROR="DELETE_PRODUCT_ERROR";